### ISSUE TITLE
Not working with OpenCV 4.5.4

### ISSUE THREAD

**Issue by X-dark** [fangfufu/Linux-Fake-Background-Webcam#169]
I get the following error when running with OpenCV 4.5.4 (works fine with OpenCV 4.5.3):

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
 terminate called after throwing an instance of 'cv::Exception'
   what():  OpenCV(4.5.4) /build/opencv/src/opencv-4.5.4/modules/core/src/matrix_wrap.cpp:1476: error: (-27:Null pointer) create() called for the missing output array in function 'create'
```

This happens as soon as I try to access the virtual webcam. 

This is on ArchLinux with Fake-Background-Webcam built from latest git commit.

**Comment by X-dark** [comment]
As I said if I downgrade to opencv and python-opencv 4.5.3 it works fine. I am not sure I could do the same in a virtualenv as I would need anyway to downgrade opencv to have it on the same version of python-opencv of the virtualenv.

Anyway, I can keep using opencv and python-opencv 4.5.3 for the time being.

I had a quicklook on opencv release notes and I cannot see an item that I could directly link to this error. So I guess deeper investigation will be needed.

**Comment by renyuneyun** [comment]
OK, I found a fix (for me at least): recompile and install `python-mediapipe-git` .
